### ISSUE TITLE
Update to new Web dispatch

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-jsonrpc#3]
The move from Webmachine to Cowboy in https://github.com/rabbitmq/rabbitmq-management/issues/63 breaks this plugin.

**Comment by essen** [comment]
This merge is a little early, considering the new Web dispatch hasn't been merged yet. :-)

**Comment by dumbbell** [comment]
Oh :) I wanted to test on rabbit-web-dev which uses this and jsonrpc-channel and jsonrpc-channel-examples (they both need conversion), so this required the merge. Anyway, let me know when this is ready.

**Comment by essen** [comment]
Ready whenever rabbitmq/rabbitmq-management#63 gets merged (currently pending review, @michaelklishin said he was going to start tomorrow).
